import { describe, it, expect } from 'vitest';
import type { RideEvent, ImportResolution } from '../contract/types';
import { EXPORT_CSV_COLUMNS } from '../contract/types';
import { buildGeoIndex } from './store';
import { JP_PACKAGE, STUB_PACKAGES } from '../fixtures/stubPackage';
import { exportEventsToCsv } from './export';
import { parseImport } from './import/parse';
import { buildImportEvents } from './import/commit';
import { parseCsv } from './import/csv';

const geo = buildGeoIndex(STUB_PACKAGES);

const EVENTS: RideEvent[] = [
  {
    id: 'a',
    segmentId: 'jr-kururi:0-1',
    railGeoVersion: JP_PACKAGE.version,
    date: '2025-03-01',
    trainModel: 'キハE130',
    source: 'manual',
    tripId: 'trip-1',
    createdAt: '2025-03-01T08:00:00.000Z',
  },
  {
    id: 'b',
    segmentId: 'jr-tokaido-shinkansen:0-1',
    railGeoVersion: JP_PACKAGE.version,
    // undated import — must survive the round-trip as empty/undefined
    source: 'import',
    importBatchId: 'old-batch',
    createdAt: '2025-04-10T09:30:00.000Z',
  },
  {
    id: 'c',
    segmentId: 'cn-jinghu-hsr:0-1',
    railGeoVersion: '2025.1.0',
    trainModel: 'CR400AF',
    source: 'corridor',
    createdAt: '2025-05-05T00:00:00.000Z',
  },
];

describe('exportEventsToCsv', () => {
  it('emits the header EXACTLY in EXPORT_CSV_COLUMNS order', () => {
    const csv = exportEventsToCsv(EVENTS, STUB_PACKAGES);
    expect(parseCsv(csv)[0].join(',')).toBe(EXPORT_CSV_COLUMNS);
  });

  it('derives a human-readable lineId and sets rode=1 on every row', () => {
    const csv = exportEventsToCsv(EVENTS, STUB_PACKAGES);
    const grid = parseCsv(csv);
    const header = grid[0];
    const iLine = header.indexOf('lineId');
    const iRode = header.indexOf('rode');
    const body = grid.slice(1);
    expect(body.every((r) => r[iRode] === '1')).toBe(true);
    // first row is the kururi event (earliest createdAt) → human-readable line name
    expect(body[0][iLine]).toBe('久留里線');
  });

  it('also accepts a GeoIndex as the lookup source', () => {
    const csv = exportEventsToCsv(EVENTS, geo);
    expect(parseCsv(csv)[0].join(',')).toBe(EXPORT_CSV_COLUMNS);
  });
});

describe('lossless round-trip: parse(export(events))', () => {
  it('preserves segmentId/source/tripId/createdAt/date/trainModel/railGeoVersion', () => {
    const csv = exportEventsToCsv(EVENTS, STUB_PACKAGES);
    const parsed = parseImport(csv, STUB_PACKAGES, geo);
    expect(parsed.reimport).toBe(true);
    const res: ImportResolution = { importBatchId: parsed.report.importBatchId, confirmed: [], skipped: [] };
    const round = buildImportEvents(parsed.resolved, res, STUB_PACKAGES);

    // Compare on the MEANINGFUL fields only (id + importBatchId are regenerated by design).
    const meaningful = (e: RideEvent) => ({
      segmentId: e.segmentId,
      railGeoVersion: e.railGeoVersion,
      source: e.source,
      tripId: e.tripId,
      createdAt: e.createdAt,
      date: e.date,
      trainModel: e.trainModel,
    });
    const norm = (xs: RideEvent[]) =>
      xs
        .map(meaningful)
        .sort((a, b) => (a.segmentId < b.segmentId ? -1 : 1));

    expect(norm(round)).toEqual(norm(EVENTS));
  });

  it('an undated event stays undated through the round-trip', () => {
    const csv = exportEventsToCsv(EVENTS, STUB_PACKAGES);
    const parsed = parseImport(csv, STUB_PACKAGES, geo);
    const res: ImportResolution = { importBatchId: parsed.report.importBatchId, confirmed: [], skipped: [] };
    const round = buildImportEvents(parsed.resolved, res, STUB_PACKAGES);
    const tokaido = round.find((e) => e.segmentId === 'jr-tokaido-shinkansen:0-1')!;
    expect(tokaido.date).toBeUndefined();
    expect(tokaido.trainModel).toBeUndefined();
  });

  it('regenerates id + importBatchId (NOT carried in the CSV)', () => {
    const csv = exportEventsToCsv(EVENTS, STUB_PACKAGES);
    expect(csv).not.toContain('old-batch'); // importBatchId is not an export column
    const parsed = parseImport(csv, STUB_PACKAGES, geo);
    const res: ImportResolution = { importBatchId: parsed.report.importBatchId, confirmed: [], skipped: [] };
    const round = buildImportEvents(parsed.resolved, res, STUB_PACKAGES);
    expect(round.every((e) => e.importBatchId === parsed.report.importBatchId)).toBe(true);
    expect(round.every((e) => e.id !== 'a' && e.id !== 'b' && e.id !== 'c')).toBe(true);
  });
});
