// 車両 model registry (v0.13 車両図鑑, plan D2/D3) — hand-curated REFERENCE DATA, facts only.
// PURE DATA MODULE: imports nothing (train-models.ts builds every derived index — alias map,
// speed table, roster counts — so no import cycle can form). Grows to a content-addressed
// rail/registry.json artifact later (Wikidata SPARQL + overrides, TODOS.md) — this shape is
// designed to graduate unchanged.
//
// Identity rules (D2, review-locked):
//  • `id` is OPERATOR-SCOPED (`jp-jre-e5`) — folds collide across operators once the roster
//    leaves HSR (東急5000 vs 京王5000), ids never do.
//  • `fold` is the canonical comparison key (canonicalizeTrainModel output) — an ALIAS-INDEX
//    lookup, never the identity. The v0.13 roster MUST be fold-collision-free (test-enforced),
//    so every raw string maps to at most one card without line/operator context.
//  • E5/H5 and E7/W7 are separate cards linked by pairId (review 10A). Denominator = 13
//    after the 2026-07 fact-check restored E2 (2026-03 改正で定期運用回復).
//  • `active` gates the roster DENOMINATOR only: inactive entries (E3) never ghost-card or
//    count in X/N, but still match rides and render as collected history.
//  • `corridor: 'jinghu'` marks the CN corridor roster (review 11B) — the CN meter counts ONLY
//    corridor models (earnable from the app's own data surface), never all-China.
//  • `accentColor` is a stylized LIVERY approximation — permitted ONLY inside silhouette fills
//    (design DD8 livery-is-data carve-out); all chrome stays emerald-system.
//
// Provenance (14A): every entry carries `source` — a fact-source note cross-checked against
// Wikipedia/Wikidata at curation time. Roster reviewed at each data sync (ロースター基準: 2026).

export type TrainCategory = 'shinkansen' | 'cn-hsr' | 'ltd-express' | 'commuter' | 'dmu';

export type SilhouetteVariant = 'shinkansen' | 'cn-hsr' | 'express' | 'commuter' | 'dmu';

export interface TrainModelInfo {
  /** Operator-scoped stable id — the identity users' collections key on. */
  id: string;
  /** Canonical fold key (= canonicalizeTrainModel(name)); unique across the registry. */
  fold: string;
  /** 形式 display name. */
  name: string;
  nameRomaji?: string;
  country: 'JP' | 'CN';
  category: TrainCategory;
  operator: string;
  /** Top service speed; omitted when not confidently known (unknowns never fake facts). */
  topSpeedKmh?: number;
  /** 愛称 this 形式 serves (D13: display resolves to candidate SETS, never auto-pick). */
  nicknames?: string[];
  /** Extra raw spellings that resolve to this entry (compared via foldKey). */
  aliases?: string[];
  /** Same-design different-operator sibling (E5↔H5, E7↔W7). */
  pairId?: string;
  debutYear?: number;
  /** In the roster denominator (shinkansen / corridor meters). */
  active: boolean;
  /** Honest urgency, facts only ('2027年1月引退予定') — never invented rarity. */
  retiresNote?: string;
  /** Stylized livery fill (DD8: silhouette fills ONLY). */
  accentColor?: string;
  silhouette: SilhouetteVariant;
  /** CN corridor roster membership (11B). */
  corridor?: 'jinghu';
  /** Provenance note (14A). */
  source: string;
}

export const ROSTER_BASIS_YEAR = 2026;

export const CATEGORY_LABELS: Record<TrainCategory, string> = {
  shinkansen: '新幹線',
  'cn-hsr': '中国高速鉄道',
  'ltd-express': '特急',
  commuter: '通勤・近郊',
  dmu: '気動車',
};

export const MODEL_REGISTRY: TrainModelInfo[] = [
  // ──────────────────── 新幹線 (active roster = 13 — fact-check 2026-07) ────────────────────
  { id: 'jp-jrc-n700s', fold: 'N700S', name: 'N700S', nameRomaji: 'N700S', country: 'JP', category: 'shinkansen', operator: 'JR東海', topSpeedKmh: 300, nicknames: ['のぞみ', 'ひかり', 'こだま'], debutYear: 2020, active: true, accentColor: '#1E50A2', silhouette: 'shinkansen', source: '東海道285/山陽300km/h — 最高運転速度は300 (ja.wikipedia N700S系; fact-check 2026-07)' },
  { id: 'jp-jrc-n700a', fold: 'N700A', name: 'N700A', country: 'JP', category: 'shinkansen', operator: 'JR東海', topSpeedKmh: 300, nicknames: ['のぞみ', 'ひかり', 'こだま'], debutYear: 2013, active: true, accentColor: '#2A5CAA', silhouette: 'shinkansen', source: '東海道・山陽新幹線 (ja.wikipedia N700系)' },
  { id: 'jp-jrw-n700', fold: 'N700', name: 'N700系', country: 'JP', category: 'shinkansen', operator: 'JR西日本・JR九州', topSpeedKmh: 300, nicknames: ['みずほ', 'さくら', 'こだま'], aliases: ['N700系7000番台', 'N700系8000番台'], debutYear: 2011, active: true, accentColor: '#3A6EA5', silhouette: 'shinkansen', source: '山陽・九州直通用 7000/8000番台が現役 (ja.wikipedia N700系7000・8000番台)' },
  { id: 'jp-jrw-500', fold: '500', name: '500系', country: 'JP', category: 'shinkansen', operator: 'JR西日本', topSpeedKmh: 285, nicknames: ['こだま'], debutYear: 1997, active: true, retiresNote: '2027年1月引退予定', accentColor: '#7A8FA6', silhouette: 'shinkansen', source: '山陽こだま運用、2027年初引退発表 (JR西日本プレス 2024)' },
  { id: 'jp-jrw-700', fold: '700', name: '700系', country: 'JP', category: 'shinkansen', operator: 'JR西日本', topSpeedKmh: 285, nicknames: ['こだま', 'ひかりレールスター'], aliases: ['700系7000番台', 'レールスター'], debutYear: 1999, active: true, accentColor: '#4E5B66', silhouette: 'shinkansen', source: '山陽 7000番台レールスターが現役 (東海道16両は2020年引退)' },
  { id: 'jp-jrk-800', fold: '800', name: '800系', country: 'JP', category: 'shinkansen', operator: 'JR九州', topSpeedKmh: 260, nicknames: ['つばめ', 'さくら'], debutYear: 2004, active: true, accentColor: '#B02A2A', silhouette: 'shinkansen', source: '九州新幹線 (ja.wikipedia 800系)' },
  { id: 'jp-jre-e5', fold: 'E5', name: 'E5系', nameRomaji: 'E5 Series', country: 'JP', category: 'shinkansen', operator: 'JR東日本', topSpeedKmh: 320, nicknames: ['はやぶさ', 'はやて', 'やまびこ', 'なすの'], pairId: 'jp-jrh-h5', debutYear: 2011, active: true, accentColor: '#00A95F', silhouette: 'shinkansen', source: '東北・北海道新幹線 320km/h (ja.wikipedia E5系・H5系)' },
  { id: 'jp-jrh-h5', fold: 'H5', name: 'H5系', country: 'JP', category: 'shinkansen', operator: 'JR北海道', topSpeedKmh: 320, nicknames: ['はやぶさ', 'はやて'], pairId: 'jp-jre-e5', debutYear: 2016, active: true, accentColor: '#008B62', silhouette: 'shinkansen', source: 'E5系同設計・彩香パープル帯 (ja.wikipedia E5系・H5系)' },
  { id: 'jp-jre-e6', fold: 'E6', name: 'E6系', country: 'JP', category: 'shinkansen', operator: 'JR東日本', topSpeedKmh: 320, nicknames: ['こまち'], debutYear: 2013, active: true, accentColor: '#C8102E', silhouette: 'shinkansen', source: '秋田新幹線 茜色 (ja.wikipedia E6系)' },
  { id: 'jp-jre-e7', fold: 'E7', name: 'E7系', country: 'JP', category: 'shinkansen', operator: 'JR東日本', topSpeedKmh: 260, nicknames: ['かがやき', 'はくたか', 'あさま', 'とき', 'たにがわ'], pairId: 'jp-jrw-w7', debutYear: 2014, active: true, accentColor: '#2A5CAA', silhouette: 'shinkansen', source: '北陸・上越新幹線 空色 (ja.wikipedia E7系・W7系)' },
  { id: 'jp-jrw-w7', fold: 'W7', name: 'W7系', country: 'JP', category: 'shinkansen', operator: 'JR西日本', topSpeedKmh: 260, nicknames: ['かがやき', 'はくたか', 'つるぎ'], pairId: 'jp-jre-e7', debutYear: 2015, active: true, accentColor: '#245089', silhouette: 'shinkansen', source: 'E7系同設計 (ja.wikipedia E7系・W7系)' },
  { id: 'jp-jre-e8', fold: 'E8', name: 'E8系', country: 'JP', category: 'shinkansen', operator: 'JR東日本', topSpeedKmh: 300, nicknames: ['つばさ'], debutYear: 2024, active: true, accentColor: '#7A4A9E', silhouette: 'shinkansen', source: '山形新幹線 2024年営業開始・300km/h (ja.wikipedia E8系)' },
  // ── E2は2026-03改正で定期運用回復（分母入り）・E3は引退済み（分母外・乗車歴は表示） ──
  { id: 'jp-jre-e2', fold: 'E2', name: 'E2系', country: 'JP', category: 'shinkansen', operator: 'JR東日本', topSpeedKmh: 275, nicknames: ['やまびこ', 'なすの', 'とき'], debutYear: 1997, active: true, retiresNote: 'E10系置換見込み（〜2030年頃）', accentColor: '#4A6FA5', silhouette: 'shinkansen', source: '2026-03改正で仙台以北の定期運用が回復・E10系まで継続見込み (tetsudo.com/column/1502; fact-check 2026-07)' },
  { id: 'jp-jre-e3', fold: 'E3', name: 'E3系', country: 'JP', category: 'shinkansen', operator: 'JR東日本', topSpeedKmh: 275, nicknames: ['つばさ'], debutYear: 1997, active: false, retiresNote: '定期運用終了（2025年12月）', accentColor: '#9AA5AE', silhouette: 'shinkansen', source: 'つばさ定期運行は2025-12-24で終了、E8系へ置換完了 (mynavi 2024-12-13; fact-check 2026-07)' },

  // ─────────────── 中国高速鉄道 (corridor='jinghu' = 京沪 meter roster, review 11B) ───────────────
  { id: 'cn-cr-cr400af', fold: 'CR400AF', name: 'CR400AF', country: 'CN', category: 'cn-hsr', operator: '中国国家鉄路集団', topSpeedKmh: 350, nicknames: ['复兴号'], debutYear: 2017, active: true, accentColor: '#C8102E', silhouette: 'cn-hsr', corridor: 'jinghu', source: '京沪高铁 350km/h 営業 (zh.wikipedia 复兴号CR400AF)' },
  { id: 'cn-cr-cr400bf', fold: 'CR400BF', name: 'CR400BF', country: 'CN', category: 'cn-hsr', operator: '中国国家鉄路集団', topSpeedKmh: 350, nicknames: ['复兴号'], debutYear: 2017, active: true, accentColor: '#B08A00', silhouette: 'cn-hsr', corridor: 'jinghu', source: '京沪高铁 350km/h 営業 (zh.wikipedia 复兴号CR400BF)' },
  { id: 'cn-cr-crh380a', fold: 'CRH380A', name: 'CRH380A', country: 'CN', category: 'cn-hsr', operator: '中国国家鉄路集団', topSpeedKmh: 350, nicknames: ['和谐号'], debutYear: 2010, active: true, accentColor: '#9AA0A6', silhouette: 'cn-hsr', source: '京沪開業時の主力だが2025-26年の同線定期運用からは撤退 — corridorタグなし (zh.wikipedia 京沪高速动车组列车; fact-check 2026-07)' },
  { id: 'cn-cr-crh380b', fold: 'CRH380B', name: 'CRH380B', country: 'CN', category: 'cn-hsr', operator: '中国国家鉄路集団', topSpeedKmh: 350, nicknames: ['和谐号'], debutYear: 2011, active: true, accentColor: '#6E7FA0', silhouette: 'cn-hsr', corridor: 'jinghu', source: '京沪高铁の現行和谐号主力 (zh.wikipedia 京沪高速动车组列车; fact-check 2026-07)' },
  { id: 'cn-cr-crh380c', fold: 'CRH380C', name: 'CRH380C', country: 'CN', category: 'cn-hsr', operator: '中国国家鉄路集団', topSpeedKmh: 350, nicknames: ['和谐号'], debutYear: 2013, active: true, accentColor: '#7B8794', silhouette: 'cn-hsr', corridor: 'jinghu', source: 'CRH380CL が京沪高铁で現役 (zh.wikipedia 京沪高速动车组列车; fact-check 2026-07)' },
  { id: 'cn-cr-cr300af', fold: 'CR300AF', name: 'CR300AF', country: 'CN', category: 'cn-hsr', operator: '中国国家鉄路集団', topSpeedKmh: 250, nicknames: ['复兴号'], debutYear: 2020, active: true, accentColor: '#4A7B8C', silhouette: 'cn-hsr', source: '250km/h 复兴号 (zh.wikipedia CR300AF)' },
  { id: 'cn-cr-cr300bf', fold: 'CR300BF', name: 'CR300BF', country: 'CN', category: 'cn-hsr', operator: '中国国家鉄路集団', topSpeedKmh: 250, nicknames: ['复兴号'], debutYear: 2020, active: true, accentColor: '#3F6E7E', silhouette: 'cn-hsr', source: '250km/h 复兴号 (zh.wikipedia CR300BF)' },
  { id: 'cn-cr-cr200j', fold: 'CR200J', name: 'CR200J', country: 'CN', category: 'cn-hsr', operator: '中国国家鉄路集団', topSpeedKmh: 160, nicknames: ['复兴号', '绿巨人'], debutYear: 2019, active: true, accentColor: '#006341', silhouette: 'cn-hsr', source: '160km/h 動力集中式・通称 绿巨人 (zh.wikipedia CR200J)' },
  { id: 'cn-cr-crh2', fold: 'CRH2', name: 'CRH2', country: 'CN', category: 'cn-hsr', operator: '中国国家鉄路集団', topSpeedKmh: 250, nicknames: ['和谐号'], debutYear: 2007, active: true, accentColor: '#5A7FBF', silhouette: 'cn-hsr', source: 'E2系ベースの和谐号 (zh.wikipedia CRH2)' },
  { id: 'cn-cr-crh3', fold: 'CRH3', name: 'CRH3', country: 'CN', category: 'cn-hsr', operator: '中国国家鉄路集団', topSpeedKmh: 350, nicknames: ['和谐号'], debutYear: 2008, active: true, accentColor: '#C0C3C7', silhouette: 'cn-hsr', source: 'Velaroベースの和谐号 (zh.wikipedia CRH3)' },

  // ────────────────────────────── 特急 (オープン式 — 分母なし) ──────────────────────────────
  { id: 'jp-jrw-285', fold: '285', name: '285系', country: 'JP', category: 'ltd-express', operator: 'JR西日本・JR東海', topSpeedKmh: 130, nicknames: ['サンライズ出雲', 'サンライズ瀬戸'], debutYear: 1998, active: true, accentColor: '#B8A05A', silhouette: 'express', source: '現存唯一の定期寝台特急 (ja.wikipedia 285系; fact-check 2026-07)' },
  { id: 'jp-jre-e353', fold: 'E353', name: 'E353系', country: 'JP', category: 'ltd-express', operator: 'JR東日本', topSpeedKmh: 130, nicknames: ['あずさ', 'かいじ'], debutYear: 2017, active: true, accentColor: '#6C4CA0', silhouette: 'express', source: '中央線特急 (ja.wikipedia E353系)' },
  { id: 'jp-jre-e259', fold: 'E259', name: 'E259系', country: 'JP', category: 'ltd-express', operator: 'JR東日本', topSpeedKmh: 130, nicknames: ['成田エクスプレス'], debutYear: 2009, active: true, accentColor: '#C22C35', silhouette: 'express', source: 'N’EX (ja.wikipedia E259系)' },
  { id: 'jp-jre-e657', fold: 'E657', name: 'E657系', country: 'JP', category: 'ltd-express', operator: 'JR東日本', topSpeedKmh: 130, nicknames: ['ひたち', 'ときわ'], debutYear: 2012, active: true, accentColor: '#C8384A', silhouette: 'express', source: '常磐線特急 (ja.wikipedia E657系)' },
  { id: 'jp-jre-e261', fold: 'E261', name: 'E261系', country: 'JP', category: 'ltd-express', operator: 'JR東日本', topSpeedKmh: 120, nicknames: ['サフィール踊り子'], debutYear: 2020, active: true, accentColor: '#274C77', silhouette: 'express', source: 'サフィール踊り子 (ja.wikipedia E261系)' },
  { id: 'jp-jre-e653', fold: 'E653', name: 'E653系', country: 'JP', category: 'ltd-express', operator: 'JR東日本', topSpeedKmh: 130, nicknames: ['しらゆき', 'いなほ'], debutYear: 1997, active: true, accentColor: '#D2691E', silhouette: 'express', source: '羽越・信越特急 (ja.wikipedia E653系)' },
  { id: 'jp-jrc-383', fold: '383', name: '383系', country: 'JP', category: 'ltd-express', operator: 'JR東海', topSpeedKmh: 130, nicknames: ['しなの'], debutYear: 1995, active: true, accentColor: '#4C6B8A', silhouette: 'express', source: '振子式しなの (ja.wikipedia 383系)' },
  { id: 'jp-jrc-hc85', fold: 'HC85', name: 'HC85系', country: 'JP', category: 'ltd-express', operator: 'JR東海', topSpeedKmh: 120, nicknames: ['ひだ', '南紀'], debutYear: 2022, active: true, accentColor: '#B4482B', silhouette: 'dmu', source: 'ハイブリッド特急 (ja.wikipedia HC85系)' },
  { id: 'jp-jrw-683', fold: '683', name: '683系', country: 'JP', category: 'ltd-express', operator: 'JR西日本', topSpeedKmh: 130, nicknames: ['サンダーバード', 'しらさぎ'], debutYear: 2001, active: true, accentColor: '#3B5EA8', silhouette: 'express', source: '北陸特急 (ja.wikipedia 683系)' },
  { id: 'jp-jrw-289', fold: '289', name: '289系', country: 'JP', category: 'ltd-express', operator: 'JR西日本', topSpeedKmh: 130, nicknames: ['こうのとり', 'くろしお'], debutYear: 2015, active: true, accentColor: '#5A7B9C', silhouette: 'express', source: '683系改造の直流特急 (ja.wikipedia 289系)' },
  { id: 'jp-jrw-287', fold: '287', name: '287系', country: 'JP', category: 'ltd-express', operator: 'JR西日本', topSpeedKmh: 130, nicknames: ['こうのとり', 'きのさき', 'くろしお'], debutYear: 2011, active: true, accentColor: '#8A9BAA', silhouette: 'express', source: '北近畿・紀勢特急 (ja.wikipedia 287系)' },
  { id: 'jp-jrw-273', fold: '273', name: '273系', country: 'JP', category: 'ltd-express', operator: 'JR西日本', topSpeedKmh: 120, nicknames: ['やくも'], debutYear: 2024, active: true, accentColor: '#9A6A3C', silhouette: 'express', source: '新型やくも ブロンズ (ja.wikipedia 273系)' },
  { id: 'jp-jrw-271', fold: '271', name: '271系', country: 'JP', category: 'ltd-express', operator: 'JR西日本', topSpeedKmh: 130, nicknames: ['はるか'], debutYear: 2020, active: true, accentColor: '#3E7CB1', silhouette: 'express', source: 'はるか増結用 (ja.wikipedia 271系)' },
  { id: 'jp-jrw-283', fold: '283', name: '283系', country: 'JP', category: 'ltd-express', operator: 'JR西日本', topSpeedKmh: 130, nicknames: ['くろしお'], debutYear: 1996, active: true, accentColor: '#2E86AB', silhouette: 'express', source: 'オーシャンアロー (ja.wikipedia 283系)' },
  { id: 'jp-jrk-787', fold: '787', name: '787系', country: 'JP', category: 'ltd-express', operator: 'JR九州', topSpeedKmh: 130, nicknames: ['リレーかもめ', 'きらめき', '36ぷらす3'], debutYear: 1992, active: true, accentColor: '#3E3A39', silhouette: 'express', source: '水戸岡デザインのメタリック特急 (ja.wikipedia 787系)' },
  { id: 'jp-jrk-883', fold: '883', name: '883系', country: 'JP', category: 'ltd-express', operator: 'JR九州', topSpeedKmh: 130, nicknames: ['ソニック'], debutYear: 1995, active: true, accentColor: '#1E4FA0', silhouette: 'express', source: '振子式ソニック (ja.wikipedia 883系)' },
  { id: 'jp-jrk-885', fold: '885', name: '885系', country: 'JP', category: 'ltd-express', operator: 'JR九州', topSpeedKmh: 130, nicknames: ['かもめ', 'ソニック'], debutYear: 2000, active: true, accentColor: '#A9AAAB', silhouette: 'express', source: '白いかもめ/ソニック (ja.wikipedia 885系)' },
  { id: 'jp-jrh-789', fold: '789', name: '789系', country: 'JP', category: 'ltd-express', operator: 'JR北海道', topSpeedKmh: 120, nicknames: ['ライラック', 'カムイ', 'すずらん'], debutYear: 2002, active: true, accentColor: '#33A3DC', silhouette: 'express', source: '道央特急 (ja.wikipedia 789系)' },
  { id: 'jp-jrh-kiha261', fold: 'キハ261', name: 'キハ261系', country: 'JP', category: 'ltd-express', operator: 'JR北海道', topSpeedKmh: 120, nicknames: ['北斗', 'おおぞら', 'とかち', '宗谷'], debutYear: 2000, active: true, accentColor: '#2456A6', silhouette: 'dmu', source: '道内主力の特急気動車 (ja.wikipedia キハ261系)' },
  { id: 'jp-jrs-8600', fold: '8600', name: '8600系', country: 'JP', category: 'ltd-express', operator: 'JR四国', topSpeedKmh: 130, nicknames: ['しおかぜ', 'いしづち'], debutYear: 2014, active: true, accentColor: '#B8452B', silhouette: 'express', source: '予讃線特急 (ja.wikipedia 8600系)' },
  { id: 'jp-jrs-2700', fold: '2700', name: '2700系', country: 'JP', category: 'ltd-express', operator: 'JR四国', topSpeedKmh: 120, nicknames: ['南風', 'うずしお', 'しまんと'], debutYear: 2019, active: true, accentColor: '#C03A2B', silhouette: 'dmu', source: '振子式特急気動車 (ja.wikipedia 2700系)' },
  { id: 'jp-kintetsu-80000', fold: '80000', name: '80000系', country: 'JP', category: 'ltd-express', operator: '近畿日本鉄道', topSpeedKmh: 130, nicknames: ['ひのとり'], debutYear: 2020, active: true, accentColor: '#7A1E2B', silhouette: 'express', source: '名阪特急ひのとり (ja.wikipedia 近鉄80000系)' },
  { id: 'jp-kintetsu-50000', fold: '50000', name: '50000系', country: 'JP', category: 'ltd-express', operator: '近畿日本鉄道', topSpeedKmh: 130, nicknames: ['しまかぜ'], debutYear: 2013, active: true, accentColor: '#2A4B9B', silhouette: 'express', source: '観光特急しまかぜ (ja.wikipedia 近鉄50000系)' },
  { id: 'jp-nankai-50000', fold: '南海50000', name: '南海50000系', country: 'JP', category: 'ltd-express', operator: '南海電気鉄道', topSpeedKmh: 120, nicknames: ['ラピート'], debutYear: 1994, active: true, accentColor: '#24406B', silhouette: 'express', source: '関空特急ラピート — 素の「50000」foldは近鉄しまかぜが持つため事業者名付き表記が正名（D2 fold衝突回避の実例）(ja.wikipedia 南海50000系)' },
  { id: 'jp-keisei-ae', fold: 'AE', name: 'AE形', country: 'JP', category: 'ltd-express', operator: '京成電鉄', topSpeedKmh: 160, nicknames: ['スカイライナー'], debutYear: 2010, active: true, accentColor: '#2456A6', silhouette: 'express', source: '在来線最速160km/h (ja.wikipedia 京成AE形)' },
  { id: 'jp-tobu-n100', fold: 'N100', name: 'N100系', country: 'JP', category: 'ltd-express', operator: '東武鉄道', topSpeedKmh: 120, nicknames: ['スペーシアX'], debutYear: 2023, active: true, accentColor: '#C9C4B6', silhouette: 'express', source: 'スペーシアX (ja.wikipedia 東武N100系)' },
  { id: 'jp-seibu-001', fold: '001', name: '001系', country: 'JP', category: 'ltd-express', operator: '西武鉄道', topSpeedKmh: 105, nicknames: ['Laview'], debutYear: 2019, active: true, accentColor: '#B7BEC6', silhouette: 'express', source: 'Laview (ja.wikipedia 西武001系)' },
  { id: 'jp-odakyu-70000', fold: '70000', name: '70000形', country: 'JP', category: 'ltd-express', operator: '小田急電鉄', topSpeedKmh: 110, nicknames: ['GSE', 'はこね'], debutYear: 2018, active: true, accentColor: '#C0453E', silhouette: 'express', source: 'ロマンスカーGSE (ja.wikipedia 小田急70000形)' },
  { id: 'jp-meitetsu-2000', fold: '2000', name: '2000系', country: 'JP', category: 'ltd-express', operator: '名古屋鉄道', topSpeedKmh: 120, nicknames: ['ミュースカイ'], debutYear: 2004, active: true, accentColor: '#2C5F9E', silhouette: 'express', source: '中部空港特急ミュースカイ (ja.wikipedia 名鉄2000系)' },

  // ───────────────────────────── 通勤・近郊 (オープン式) ─────────────────────────────
  { id: 'jp-jre-e235', fold: 'E235', name: 'E235系', country: 'JP', category: 'commuter', operator: 'JR東日本', nicknames: ['山手線'], debutYear: 2015, active: true, accentColor: '#9ACD32', silhouette: 'commuter', source: '山手線・横須賀総武快速 (ja.wikipedia E235系)' },
  { id: 'jp-jre-e233', fold: 'E233', name: 'E233系', country: 'JP', category: 'commuter', operator: 'JR東日本', debutYear: 2006, active: true, accentColor: '#F68B1E', silhouette: 'commuter', source: '首都圏主力通勤形 (ja.wikipedia E233系)' },
  { id: 'jp-jre-e231', fold: 'E231', name: 'E231系', country: 'JP', category: 'commuter', operator: 'JR東日本', debutYear: 2000, active: true, accentColor: '#F8B500', silhouette: 'commuter', source: '首都圏通勤・近郊形 (ja.wikipedia E231系)' },
  { id: 'jp-jrw-323', fold: '323', name: '323系', country: 'JP', category: 'commuter', operator: 'JR西日本', nicknames: ['大阪環状線'], debutYear: 2016, active: true, accentColor: '#F39700', silhouette: 'commuter', source: '大阪環状線 (ja.wikipedia 323系)' },
  { id: 'jp-jrc-313', fold: '313', name: '313系', country: 'JP', category: 'commuter', operator: 'JR東海', debutYear: 1999, active: true, accentColor: '#F77321', silhouette: 'commuter', source: '東海圏近郊形 (ja.wikipedia 313系)' },
  { id: 'jp-jrw-227', fold: '227', name: '227系', country: 'JP', category: 'commuter', operator: 'JR西日本', nicknames: ['Red Wing'], debutYear: 2015, active: true, accentColor: '#E60012', silhouette: 'commuter', source: '広島・和歌山地区 (ja.wikipedia 227系)' },

  // ─────────────────────────────── 気動車 (オープン式) ───────────────────────────────
  { id: 'jp-jr-kiha40', fold: 'キハ40', name: 'キハ40系', country: 'JP', category: 'dmu', operator: 'JR各社', debutYear: 1977, active: true, retiresNote: '各地で置換・引退進行中', accentColor: '#D86018', silhouette: 'dmu', source: '国鉄形一般気動車・タラコ色 (ja.wikipedia キハ40系)' },
  { id: 'jp-jre-kihae130', fold: 'キハE130', name: 'キハE130系', country: 'JP', category: 'dmu', operator: 'JR東日本', debutYear: 2007, active: true, accentColor: '#3E92CC', silhouette: 'dmu', source: '水郡線ほか (ja.wikipedia キハE130系)' },
  { id: 'jp-jre-gve400', fold: 'GVE400', name: 'GV-E400系', country: 'JP', category: 'dmu', operator: 'JR東日本', debutYear: 2019, active: true, accentColor: '#8B9DA8', silhouette: 'dmu', source: '電気式気動車 — ハイフン表記はfoldが吸収 (ja.wikipedia GV-E400系)' },
  { id: 'jp-jre-kiha110', fold: 'キハ110', name: 'キハ110系', country: 'JP', category: 'dmu', operator: 'JR東日本', debutYear: 1990, active: true, accentColor: '#2E8B57', silhouette: 'dmu', source: 'ローカル線主力気動車 (ja.wikipedia キハ110系)' },

  // ── 2026-07-11 expansion: full active-roster sweep (user: the 63-entry registry was not a
  // thorough model of trains). 10-group multi-agent web research + full-model cross-examination
  // (62 corrections applied) + omissions fact-check pass; same discipline as the original 63:
  // regular scheduled service mid-2026, family-level cards, per-entry provenance. ──
  { id: 'jp-jrh-kiha283', fold: 'キハ283', name: 'キハ283系', country: 'JP', category: 'ltd-express', operator: 'JR北海道', topSpeedKmh: 110, nicknames: ['オホーツク'], aliases: ['キハ283系オホーツク編成'], debutYear: 1997, active: true, accentColor: '#E60012', silhouette: 'express', source: 'ja.wikipedia.org/wiki/JR北海道キハ283系気動車; railf.jp 2023-03-18 news on キハ283系 taking over オホーツク/大雪; railf.jp 2025-03-15 on 大雪\'s downgrade to rapid' },
  { id: 'jp-jre-e257', fold: 'E257', name: 'E257系', country: 'JP', category: 'ltd-express', operator: 'JR東日本', topSpeedKmh: 130, nicknames: ['踊り子', '草津・四万', 'あかぎ', 'わかしお', 'さざなみ', 'しおさい(一部列車)'], aliases: ['E257系0番台', 'E257系500番台', 'E257系2000番台', 'E257系2500番台', 'E257系5000番台', 'E257系5500番台'], debutYear: 2001, active: true, accentColor: '#F39800', silhouette: 'express', source: 'ja.wikipedia.org/wiki/E257系 + JR東日本公式列車ページ (草津・四万/あかぎ, わかしお/さざなみ/しおさい)' },
  { id: 'jp-jrc-373', fold: '373', name: '373系', country: 'JP', category: 'ltd-express', operator: 'JR東海', topSpeedKmh: 120, nicknames: ['ふじかわ', '伊那路', 'ホームライナー'], debutYear: 1995, active: true, accentColor: '#1B7B3A', silhouette: 'express', source: 'ja.wikipedia.org/JR東海373系電車; railway.jr-central.co.jp/train/express/detail_02_03/ (運行区間: ふじかわ 静岡~甲府, 伊那路 豊橋~飯田, ホームライナー 静岡地区)' },
  { id: 'jp-jrw-281', fold: '281', name: '281系', country: 'JP', category: 'ltd-express', operator: 'JR西日本', topSpeedKmh: 130, nicknames: ['はるか'], debutYear: 1994, active: true, accentColor: '#7B2D8E', silhouette: 'express', source: 'ja.wikipedia.org/wiki/JR西日本281系電車; mynavi.jp 2026-05 article confirms 281/271 are still はるか\'s primary+supplement fleet with new-vehicle plan not yet delivered' },
  { id: 'jp-jrw-681', fold: '681', name: '681系', country: 'JP', category: 'ltd-express', operator: 'JR西日本', topSpeedKmh: 130, nicknames: ['しらさぎ'], aliases: ['681系0番台', '681系2000番台'], debutYear: 1992, active: true, retiresNote: 'Down to ~3 sets of 0番台 + 1 set of 2000番台 on しらさぎ as of mid-2026; 683系 replacement stalled on car-shortage (283系 retirement/289系 reflow being the likely eventual trigger) — still in genuine regular service, not yet retired.', accentColor: '#652D90', silhouette: 'express', source: 'ja.wikipedia.org/wiki/JR西日本681系電車; kumoyuni45.net 2026 tracking piece on remaining しらさぎ 681系 sets after 2024 Hokuriku Shinkansen Tsuruga extension shrank the 681/683 pool' },
  { id: 'jp-jrw-kiha189', fold: 'キハ189', name: 'キハ189系', country: 'JP', category: 'ltd-express', operator: 'JR西日本', topSpeedKmh: 130, nicknames: ['はまかぜ', 'らくラクびわこ(間合い運用)'], debutYear: 2010, active: true, accentColor: '#C8102E', silhouette: 'express', source: 'ja.wikipedia.org/wiki/JR西日本キハ189系気動車; tetsumin.com series feature confirms 2026-03 timetable with Osaka-Tottori/Kasumi/Toyooka/Kinosaki-Onsen workings, H1-H7 sets at Suita-Kyoto' },
  { id: 'jp-jrw-kiha187', fold: 'キハ187', name: 'キハ187系', country: 'JP', category: 'ltd-express', operator: 'JR西日本', topSpeedKmh: 120, nicknames: ['スーパーおき', 'スーパーまつかぜ', 'スーパーいなば'], aliases: ['キハ187系0番台', 'キハ187系100番台'], debutYear: 2001, active: true, accentColor: '#F39800', silhouette: 'express', source: 'ja.wikipedia.org/wiki/スーパーまつかぜ; nrtlog.com service-comparison piece confirming スーパーおき runs San\'in-line through to Shin-Yamaguchi (山陽線 tail) while スーパーまつかぜ stays within San\'in line Tottori-Masuda' },
  { id: 'jp-chizu-hot7000', fold: 'HOT7000', name: 'HOT7000系', country: 'JP', category: 'ltd-express', operator: '智頭急行', topSpeedKmh: 130, nicknames: ['スーパーはくと'], aliases: ['智頭急行HOT7000系'], debutYear: 1994, active: true, accentColor: '#2B5FA3', silhouette: 'express', source: 'ja.wikipedia.org/wiki/智頭急行HOT7000系気動車; chizukyu.co.jp official スーパーはくと vehicle page confirms Kyoto/Osaka-Tottori/Kurayoshi through-running via JR San\'yō + Chizu-kyū + JR San\'in lines' },
  { id: 'jp-jrs-8000', fold: '8000', name: '8000系', country: 'JP', category: 'ltd-express', operator: 'JR四国', topSpeedKmh: 130, nicknames: ['しおかぜ', 'いしづち'], aliases: ['8000系特急型電車', 'N8000系(更新車)'], debutYear: 1992, active: true, accentColor: '#F39800', silhouette: 'express', source: 'ja.wikipedia.org/wiki/JR四国8000系電車; jr-shikoku.co.jp vehicle page — 1993 production debut replacing DMU しおかぜ/いしづち services, controlled pendulum tilt, 130km/h on 800m+ curves' },
  { id: 'jp-jrs-2600', fold: '2600', name: '2600系', country: 'JP', category: 'ltd-express', operator: 'JR四国', topSpeedKmh: 120, nicknames: ['うずしお'], aliases: ['2600系気動車'], debutYear: 2017, active: true, accentColor: '#4A90D9', silhouette: 'express', source: 'ja.wikipedia.org/wiki/JR四国2600系気動車; shikoku-railway-note.com — only 4 cars built (2017) after air-spring tilt issues on the 土讃線 halted mass production; now fills in on しまんと/いしづち busy-season legs and some うずしお runs' },
  { id: 'jp-jrs-kiha185', fold: 'キハ185', name: 'キハ185系', country: 'JP', category: 'ltd-express', operator: 'JR四国', topSpeedKmh: 100, nicknames: ['剣山', 'やくおうじ(臨時)'], aliases: ['国鉄キハ185系', '四国色キハ185'], debutYear: 1986, active: true, accentColor: '#00A0DE', silhouette: 'express', source: 'ja.wikipedia.org/wiki/国鉄キハ185系気動車; train-times.net / shikoku-railway-note.com 2026 — down to 3.5 round trips on 特急剣山 after March 2025 revision dropped むろと and cut 剣山 frequency; surplus units increasingly diverted to JR九州 transfer and event trains' },
  { id: 'jp-jrk-783', fold: '783', name: '783系', country: 'JP', category: 'ltd-express', operator: 'JR九州', topSpeedKmh: 130, nicknames: ['みどり', 'ハウステンボス'], aliases: ['ハイパーサルーン'], debutYear: 1988, active: true, accentColor: '#F39800', silhouette: 'express', source: 'ja.wikipedia.org/wiki/JR九州783系電車; toyokeizai.net 2025 feature — JR\'s first 特急 EMU with center-entry doors and rotating seats; since the 2022 西九州新幹線 opening, confined to みどり/ハウステンボス pairings (11 round trips as of March 2025)' },
  { id: 'jp-jrk-kiha71', fold: 'キハ71', name: 'キハ71系', country: 'JP', category: 'ltd-express', operator: 'JR九州', topSpeedKmh: 120, nicknames: ['ゆふいんの森'], aliases: ['キハ72系(新ゆふいんの森/ゆふいんの森III世)'], debutYear: 1989, active: true, accentColor: '#2E4E3F', silhouette: 'express', source: 'ja.wikipedia.org/wiki/JR九州キハ71系気動車; ja.wikipedia.org/wiki/JR九州キハ72系気動車; toretabi.jp — キハ71系 debuted March 1989 for the 久大本線 resort 特急ゆふいんの森 between Fukuoka/Kitakyushu and Yufuin/Oita; キハ72系ですthe 1999 higher-capacity 5-car follow-on sharing the same design lineage and named train, folded in here as one rider-facing family' },
  { id: 'jp-tobu-500', fold: '東武500', name: '東武500系', country: 'JP', category: 'ltd-express', operator: '東武鉄道', topSpeedKmh: 120, nicknames: ['リバティ', 'Revaty'], aliases: ['リバティけごん', 'リバティきぬ', 'リバティ会津', 'リバティりょうもう', '東武500系(リバティ)'], debutYear: 2017, active: true, accentColor: '#C9B896', silhouette: 'express', source: 'ja.wikipedia.org/東武500系電車; tobu.co.jp special_express/vehicle/revaty — 2017 debut, 120km/h service max, Nikko/Kinugawa/Isesaki/Noda lines + Aizu through-service' },
  { id: 'jp-tobu-200', fold: '東武200', name: '東武200系', country: 'JP', category: 'ltd-express', operator: '東武鉄道', topSpeedKmh: 110, nicknames: ['りょうもう', 'Ryomo'], aliases: ['200形(基本番台)', '250形', '東武200系(りょうもう)'], debutYear: 1991, active: true, accentColor: '#C41E3A', silhouette: 'express', source: 'ja.wikipedia.org/東武200系電車; tobu.co.jp special_express/vehicle/ryomo — 1991 debut (rebuilt from 1720系), 110km/h, Asakusa–Akagi via Isesaki/Kiryu lines, still in regular 特急りょうもう service mid-2026' },
  { id: 'jp-tobu-100', fold: '東武100', name: '東武100系', country: 'JP', category: 'ltd-express', operator: '東武鉄道', topSpeedKmh: 120, nicknames: ['スペーシア', 'SPACIA'], aliases: ['スペーシア雅', 'スペーシア日光詣', '東武100系(スペーシア)'], debutYear: 1990, active: true, retiresNote: 'Gradual retirement in progress as N100系スペーシアX replaces sets one-by-one (104F 2022, 105F 2023, 101F 2024); 6 of 9 original sets still in daily service mid-2026, full retirement date not yet announced', accentColor: '#7B1F3A', silhouette: 'express', source: 'ja.wikipedia.org/東武100系電車; tetsudo-ch.com 2026 column on 100系 phased retirement — 1990 debut, 120km/h, Nikko/Kinugawa lines plus Skytree Liner' },
  { id: 'jp-odakyu-30000', fold: '小田急30000', name: '小田急30000形', country: 'JP', category: 'ltd-express', operator: '小田急電鉄', topSpeedKmh: 110, nicknames: ['EXE', 'EXEα'], aliases: ['EXEα(リニューアル車)', '小田急30000形(EXE)'], debutYear: 1996, active: true, accentColor: '#E4501E', silhouette: 'express', source: 'ja.wikipedia.org/小田急30000形電車; odakyu.jp EXE 30th-anniversary (2026-03-23) — 1996 debut, 110km/h, Odakyu main/Enoshima lines with Hakone-Tozan through-service' },
  { id: 'jp-odakyu-60000', fold: '小田急60000', name: '小田急60000形', country: 'JP', category: 'ltd-express', operator: '小田急電鉄', topSpeedKmh: 110, nicknames: ['MSE'], aliases: ['小田急60000形(MSE)'], debutYear: 2008, active: true, accentColor: '#1E3A5F', silhouette: 'express', source: 'ja.wikipedia.org/小田急60000形電車; tetsudo.com event listings May–June 2026 on MSE service changes — 2008 debut, 110km/h on Odakyu lines (80km/h under Tokyo Metro), first reserved-seat limited express with subway through-running (Chiyoda line), plus JR Gotemba line since 2012' },
  { id: 'jp-keikyu-2100', fold: '京急2100', name: '京急2100形', country: 'JP', category: 'ltd-express', operator: '京浜急行電鉄', topSpeedKmh: 120, nicknames: ['ドレミファインバータ'], aliases: ['KEIKYU BLUE SKY TRAIN(2133編成)'], debutYear: 1998, active: true, accentColor: '#E60012', silhouette: 'express', source: 'ja.wikipedia.org/京急2100形電車 — 1998 debut, 120km/h, 2-door cross-seat flagship running 快特 on Main/Kurihama lines, Siemens inverter \'singing train\' nickname' },
  { id: 'jp-kintetsu-21000', fold: '近鉄21000', name: '近鉄21000系', country: 'JP', category: 'ltd-express', operator: '近畿日本鉄道', topSpeedKmh: 130, nicknames: ['アーバンライナー', 'アーバンライナーplus'], aliases: ['21020系', 'アーバンライナーnext', '近鉄21000系(アーバンライナー)'], debutYear: 1988, active: true, accentColor: '#F07800', silhouette: 'express', source: 'ja.wikipedia.org/wiki/近鉄21000系電車, cross-checked with 近鉄公式 車両紹介' },
  { id: 'jp-kintetsu-30000', fold: '近鉄30000', name: '近鉄30000系', country: 'JP', category: 'ltd-express', operator: '近畿日本鉄道', topSpeedKmh: 120, nicknames: ['ビスタEX'], aliases: ['ビスタカーIII世', '近鉄30000系(ビスタEX)'], debutYear: 1978, active: true, accentColor: '#D2601A', silhouette: 'express', source: 'ja.wikipedia.org/wiki/近鉄30000系電車; 2024年時点の配置本数を確認' },
  { id: 'jp-kintetsu-26000', fold: '近鉄26000', name: '近鉄26000系', country: 'JP', category: 'ltd-express', operator: '近畿日本鉄道', topSpeedKmh: 110, nicknames: ['さくらライナー'], aliases: ['近鉄26000系(さくらライナー)'], debutYear: 1990, active: true, accentColor: '#F4A6C6', silhouette: 'express', source: 'ja.wikipedia.org/wiki/近鉄26000系電車' },
  { id: 'jp-kintetsu-23000', fold: '近鉄23000', name: '近鉄23000系', country: 'JP', category: 'ltd-express', operator: '近畿日本鉄道', topSpeedKmh: 130, nicknames: ['伊勢志摩ライナー'], aliases: ['近鉄23000系(伊勢志摩ライナー)'], debutYear: 1994, active: true, accentColor: '#E4002B', silhouette: 'express', source: 'ja.wikipedia.org/wiki/近鉄23000系電車; 2024年時点で6編成36両全車運用中を確認' },
  { id: 'jp-kintetsu-22000', fold: '近鉄22000', name: '近鉄22000系', country: 'JP', category: 'ltd-express', operator: '近畿日本鉄道', topSpeedKmh: 130, nicknames: ['ACE', 'Advanced Comfortable Express'], aliases: ['22600系(Ace)', '近鉄22000系(ACE)'], debutYear: 1992, active: true, accentColor: '#FFD400', silhouette: 'express', source: 'ja.wikipedia.org/wiki/近鉄22000系電車; 標準軌用22600系は同ブランドの後継形式としてaliasesに集約' },
  { id: 'jp-kintetsu-16600', fold: '近鉄16600', name: '近鉄16600系', country: 'JP', category: 'ltd-express', operator: '近畿日本鉄道', topSpeedKmh: 110, nicknames: ['Ace'], aliases: ['近鉄16600系(Ace)'], debutYear: 2010, active: true, accentColor: '#F39800', silhouette: 'express', source: 'ja.wikipedia.org/wiki/近鉄16600系電車 — 22600系の狭軌仕様版と明記' },
  { id: 'jp-nankai-30000', fold: '南海30000', name: '南海30000系', country: 'JP', category: 'ltd-express', operator: '南海電気鉄道', topSpeedKmh: 100, nicknames: ['こうや', 'りんかん', 'レッドこうや', 'パープルこうや'], aliases: ['31000系', '南海30000系・31000系(こうや/りんかん)'], debutYear: 1983, active: true, accentColor: '#7B1631', silhouette: 'express', source: 'ja.wikipedia.org/wiki/南海30000系電車 + 南海31000系電車; 2025年4月時点の在籍数を確認' },
  { id: 'jp-nankai-12000', fold: '南海12000', name: '南海12000系', country: 'JP', category: 'ltd-express', operator: '南海電気鉄道', topSpeedKmh: 110, nicknames: ['サザン・プレミアム'], aliases: ['南海12000系(サザン・プレミアム)'], debutYear: 2011, active: true, accentColor: '#0068B7', silhouette: 'express', source: 'ja.wikipedia.org/wiki/南海12000系電車; 2025年4月の泉北高速鉄道合併後の在籍を確認' },
  { id: 'jp-meitetsu-2200', fold: '名鉄2200', name: '名鉄2200系', country: 'JP', category: 'ltd-express', operator: '名古屋鉄道', topSpeedKmh: 120, nicknames: [], debutYear: 2005, active: true, accentColor: '#E2231A', silhouette: 'express', source: 'ja.wikipedia.org/wiki/名鉄2200系電車' },
  { id: 'jp-meitetsu-1200', fold: '名鉄1200', name: '名鉄1200系', country: 'JP', category: 'ltd-express', operator: '名古屋鉄道', topSpeedKmh: 120, nicknames: ['パノラマスーパー'], aliases: ['1000系', '名鉄1000系・1200系(パノラマスーパー)'], debutYear: 1988, active: true, accentColor: '#D6002A', silhouette: 'express', source: 'ja.wikipedia.org/wiki/名鉄1000系電車 — 全車特別車の1000系単独編成は2008年に運用終了、現存は1000-1200系(一部特別車)のみ' },
  { id: 'jp-keihan-8000', fold: '京阪8000', name: '京阪8000系', country: 'JP', category: 'ltd-express', operator: '京阪電気鉄道', topSpeedKmh: 110, nicknames: ['プレミアムカー'], aliases: ['京阪8000系(プレミアムカー)'], debutYear: 1989, active: true, accentColor: '#C8102E', silhouette: 'express', source: 'ja.wikipedia.org/wiki/京阪8000系電車; プレミアムカー導入2017年8月を確認' },
  { id: 'jp-keihan-3000', fold: '京阪3000', name: '京阪3000系', country: 'JP', category: 'ltd-express', operator: '京阪電気鉄道', topSpeedKmh: 110, nicknames: ['洛楽', 'プレミアムカー'], aliases: ['京阪3000系(プレミアムカー)'], debutYear: 2008, active: true, accentColor: '#1B3A6B', silhouette: 'express', source: 'ja.wikipedia.org/wiki/京阪3000系電車_(2代); プレミアムカー2両編成化(2025年10月)を確認' },
  { id: 'jp-hankyu-2300', fold: '阪急2300', name: '阪急2300系', country: 'JP', category: 'ltd-express', operator: '阪急電鉄', topSpeedKmh: 115, nicknames: ['PRiVACE'], aliases: ['阪急2300系(PRiVACE)'], debutYear: 2024, active: true, accentColor: '#6F2C3F', silhouette: 'express', source: 'ja.wikipedia.org/wiki/阪急2300系電車_(2代); 2026年4月時点の運用両数を確認' },
  { id: 'jp-hankyu-9300', fold: '阪急9300', name: '阪急9300系', country: 'JP', category: 'ltd-express', operator: '阪急電鉄', topSpeedKmh: 115, nicknames: ['PRiVACE'], aliases: ['阪急9300系(PRiVACE編成)'], debutYear: 2003, active: true, accentColor: '#6F2C3F', silhouette: 'express', source: 'ja.wikipedia.org/wiki/阪急9300系電車; 2026年4月時点で11本88両、うち5本にPRiVACE連結を確認' },
  { id: 'jp-nishitetsu-3000', fold: '西鉄3000', name: '西鉄3000形', country: 'JP', category: 'ltd-express', operator: '西日本鉄道', topSpeedKmh: 110, nicknames: ['水都(柳川観光列車)', '旅人(太宰府観光列車)'], debutYear: 2006, active: true, accentColor: '#0068B7', silhouette: 'express', source: 'ja.wikipedia.org/wiki/西鉄3000形電車; 日中特急は原則3000形運行と確認' },
  { id: 'jp-fujikyu-8500', fold: '富士急8500', name: '富士急8500系', country: 'JP', category: 'ltd-express', operator: '富士山麓電気鉄道', topSpeedKmh: 70, nicknames: ['富士山ビュー特急'], aliases: ['元JR東海371系'], debutYear: 2016, active: true, accentColor: '#16305A', silhouette: 'express', source: 'ja.wikipedia 富士山麓電気鉄道; response.jp 2016/04/06 report' },
  { id: 'jp-fujikyu-8000', fold: '富士急8000', name: '富士急8000系', country: 'JP', category: 'ltd-express', operator: '富士山麓電気鉄道', topSpeedKmh: 70, nicknames: ['フジサン特急'], aliases: ['元小田急20000形RSE'], debutYear: 2014, active: true, accentColor: '#E8432A', silhouette: 'express', source: 'ja.wikipedia 富士山麓電気鉄道; fujikyu-railway.jp fujisan-express-15anniversary' },
  { id: 'jp-nagaden-2100', fold: '長野電鉄2100', name: '長野電鉄2100系', country: 'JP', category: 'ltd-express', operator: '長野電鉄', topSpeedKmh: 90, nicknames: ['スノーモンキー'], aliases: ['元JR253系(初代成田エクスプレス)'], debutYear: 2011, active: true, accentColor: '#2F5233', silhouette: 'express', source: 'ja.wikipedia 長野電鉄2100系電車' },
  { id: 'jp-nagaden-1000', fold: '長野電鉄1000', name: '長野電鉄1000系', country: 'JP', category: 'ltd-express', operator: '長野電鉄', topSpeedKmh: 90, nicknames: ['ゆけむり'], aliases: ['元小田急10000形HiSE'], debutYear: 2006, active: true, accentColor: '#7C1F2E', silhouette: 'express', source: 'ja.wikipedia 長野電鉄1000系電車' },
  { id: 'jp-tantetsu-ktr8000', fold: 'KTR8000', name: 'KTR8000形', country: 'JP', category: 'ltd-express', operator: '京都丹後鉄道', topSpeedKmh: 120, nicknames: ['丹後の海'], aliases: ['京都丹後鉄道KTR8000形'], debutYear: 1996, active: true, retiresNote: '後継特急車両の導入が2026年1月発表、2028年度から2年おきに1編成ずつ計4編成を投入予定（一部KTR8000形は改修の上存続の可能性）', accentColor: '#0B3D62', silhouette: 'express', source: 'ja.wikipedia 北近畿タンゴ鉄道KTR8000形気動車; trafficnews.jp/post/629892' },
  { id: 'jp-jrs-2000', fold: '四国2000', name: '四国2000系', country: 'JP', category: 'ltd-express', operator: 'JR四国', topSpeedKmh: 130, nicknames: ['宇和海', 'あしずり'], aliases: ['N2000系'], debutYear: 1989, active: true, retiresNote: '2700系置換で南風・しまんと・うずしお・剣山・むろとから撤退済み（〜2021）、残存は宇和海・あしずり系統。後継計画未発表ながら車齢30年級で初期車廃車進行中', accentColor: '#1A2B4C', silhouette: 'express', source: '世界初の振子式気動車（TSE 1989-03営業開始・量産1990〜）。N2000系（1998〜、130km/h）は同一形式内の改良グループでエイリアス統合（独立形式付与なし、公式ページも同一）。現行は宇和海（松山〜宇和島、全列車が内子線経由）ほぼ専属＋土讃線あしずり定期4往復（高知〜中村・宿毛、以遠は土佐くろしお中村線） (ja.wikipedia 2000系・宇和海・あしずり; jr-shikoku.co.jp 2000系; shikoku-railway-note.com; raillab.jp 1431; fact-check 2026-07)' },
  { id: 'jp-kintetsu-16000', fold: '近鉄16000', name: '近鉄16000系', country: 'JP', category: 'ltd-express', operator: '近畿日本鉄道', topSpeedKmh: 110, nicknames: ['吉野特急'], debutYear: 1965, active: true, retiresNote: '2024〜25年に相次ぎ廃車（16008F+16051F・16007F）、2026-04時点の残存は16009F（2両）1本のみ。引退日未発表ながら終焉間近', accentColor: '#FFCC00', silhouette: 'express', source: '現役最古参の特急形（1965-03-18営業開始、大阪阿部野橋〜吉野）。狭軌1067mmの南大阪線・吉野線専用で、標準軌の橿原線・京都線側とは橿原神宮前で線路が繋がらず京都〜吉野系統には入らない (ja.wikipedia 近鉄16000系; kintetsu.jp/kouhou/Train/B07; tetsudo.com column/1209; toyokeizai 839017; fact-check 2026-07)' },
  { id: 'jp-jrh-721', fold: '721', name: '721系', country: 'JP', category: 'commuter', operator: 'JR北海道', topSpeedKmh: 120, nicknames: ['快速エアポート', '特別快速エアポート'], aliases: ['721系0番台', '721系1000番台', '721系3000番台(uシート)', '721系4000番台', '721系5000番台'], debutYear: 1988, active: true, retiresNote: 'JR北海道は2030年度(FY2030)までの721系全廃方針を表明済み — 2026年半ば時点では毎日運用継続', accentColor: '#1B813E', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR北海道721系電車; jrhokkaido.co.jp train guide tr020_01 (エアポート運用車両案内)' },
  { id: 'jp-jrh-731', fold: '731', name: '731系', country: 'JP', category: 'commuter', operator: 'JR北海道', topSpeedKmh: 120, nicknames: [], aliases: ['731系0番台'], debutYear: 1996, active: true, accentColor: '#00A0DE', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR北海道731系電車; katomodels.com 731系<いしかりライナー> product page' },
  { id: 'jp-jrh-733', fold: '733', name: '733系', country: 'JP', category: 'commuter', operator: 'JR北海道', topSpeedKmh: 120, nicknames: ['快速エアポート', '特別快速エアポート'], aliases: ['733系0番台', '733系100番台', '733系1000番台', '733系3000番台(uシート/エアポート仕様)', '733系4000番台'], debutYear: 2012, active: true, accentColor: '#F39800', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR北海道733系電車; jrhokkaido.co.jp train guide tr020_01 (エアポート 721系・733系)' },
  { id: 'jp-jrh-735', fold: '735', name: '735系', country: 'JP', category: 'commuter', operator: 'JR北海道', topSpeedKmh: 120, nicknames: [], aliases: ['735系0番台'], debutYear: 2010, active: true, accentColor: '#128041', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR北海道735系電車; toretabi.jp 735系(JR北海道) feature article' },
  { id: 'jp-jrh-737', fold: '737', name: '737系', country: 'JP', category: 'commuter', operator: 'JR北海道', topSpeedKmh: 120, nicknames: [], aliases: ['737系0番台'], debutYear: 2023, active: true, accentColor: '#00A497', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR北海道737系電車; 2nd-train.net 737系編成表; mynavi.jp 2023-05-28 room debut report' },
  { id: 'jp-jre-e131', fold: 'E131', name: 'E131系', country: 'JP', category: 'commuter', operator: 'JR東日本', topSpeedKmh: 100, nicknames: [], aliases: ['E131系500番台(相模線)', 'E131系600番台(宇都宮線・日光線)', 'E131系0番台(房総)', 'E131系1000番台(鶴見線)', 'E131系4000番台(仙石線)', 'E131系5000番台(中央線ほか)'], debutYear: 2021, active: true, accentColor: '#00A95F', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR東日本E131系電車 + JR東日本プレスリリース(2026年5月7日, 中央本線・篠ノ井線・信越本線投入)' },
  { id: 'jp-jre-701', fold: '701', name: '701系', country: 'JP', category: 'commuter', operator: 'JR東日本', topSpeedKmh: 110, nicknames: ['ロングシート地獄(俗称)'], aliases: ['701系0番台', '701系5000番台', '701系5500番台(山形線)', '701系1000番台', '701系1500番台'], debutYear: 1993, active: true, accentColor: '#E60012', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR東日本701系電車 + JR東日本公式列車ページ' },
  { id: 'jp-jre-e721', fold: 'E721', name: 'E721系', country: 'JP', category: 'commuter', operator: 'JR東日本', topSpeedKmh: 110, nicknames: [], aliases: ['E721系0番台', 'E721系500番台(仙台空港アクセス)', 'E721系1000番台(719系置換)'], debutYear: 2007, active: true, accentColor: '#0072BC', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR東日本E721系電車 + 河北新報 (2026年2月, 台車ひび報道)' },
  { id: 'jp-jre-e129', fold: 'E129', name: 'E129系', country: 'JP', category: 'commuter', operator: 'JR東日本', topSpeedKmh: 100, nicknames: [], debutYear: 2014, active: true, accentColor: '#E75297', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR東日本E129系電車 + JR東日本公式列車ページ' },
  { id: 'jp-jre-209', fold: '209', name: '209系', country: 'JP', category: 'commuter', operator: 'JR東日本', topSpeedKmh: 100, nicknames: [], aliases: ['209系2000番台(房総)', '209系2100番台(房総)', '209系3000番台(南武線)', '209系3100番台(南武線)'], debutYear: 1993, active: true, retiresNote: '房総地区はE131系・E233系への置換が2026年も継続中、順次縮小', accentColor: '#FFF100', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR東日本209系電車 + 4gousya.net 配置歴/置き換え記録' },
  { id: 'jp-jre-719', fold: '719', name: '719系', country: 'JP', category: 'commuter', operator: 'JR東日本', topSpeedKmh: 110, nicknames: [], aliases: ['719系5000番台'], debutYear: 1989, active: true, retiresNote: '2026年秋からE723系5000番台への置換が開始予定 — 残り約12編成、完全引退が近い', accentColor: '#2CA6A4', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR東日本719系電車 + tetutoo28m32.hateblo.jp(2025年11月, E723系5000番台導入発表)' },
  { id: 'jp-jre-e501', fold: 'E501', name: 'E501系', country: 'JP', category: 'commuter', operator: 'JR東日本', topSpeedKmh: 120, nicknames: [], debutYear: 1995, active: true, retiresNote: '2025年3月改正で土浦以南から撤退、水戸以北のみで縮小運用中 — サハ抜き取り編成の一部がJR九州へ譲渡予定(2028年春運行開始)', accentColor: '#0068B7', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR東日本E501系電車 + Yahoo!ニュース エキスパート記事(清水要, 2025年3月改正)' },
  { id: 'jp-jrc-315', fold: '315', name: '315系', country: 'JP', category: 'commuter', operator: 'JR東海', topSpeedKmh: 130, nicknames: [], aliases: ['315系0番台', '315系B編成(4両)', '315系C編成(8両)'], debutYear: 2021, active: true, accentColor: '#F39800', silhouette: 'commuter', source: 'ja.wikipedia.org/JR東海315系電車; railway.jr-central.co.jp/315s/; 2026-03-14 diagram revision completed full 315系 rollout on 武豊線・関西線 (train-times.net)' },
  { id: 'jp-jrw-223', fold: '223', name: '223系', country: 'JP', category: 'commuter', operator: 'JR西日本', topSpeedKmh: 130, nicknames: ['新快速', '関空快速', 'はるか代走'], aliases: ['223系0番台', '223系1000番台', '223系2000番台', '223系2500番台', '223系5000番台', '223系6000番台'], debutYear: 1994, active: true, accentColor: '#1155CC', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR西日本223系電車; toretabi.jp entry-8522 — cross-checked 130km/h 新快速 role and multi-番台 fleet, mid-2026 still primary 新快速 stock' },
  { id: 'jp-jrw-225', fold: '225', name: '225系', country: 'JP', category: 'commuter', operator: 'JR西日本', topSpeedKmh: 130, nicknames: ['新快速', '紀州路快速'], aliases: ['225系0番台', '225系100番台', '225系5000番台', '225系6000番台'], debutYear: 2010, active: true, accentColor: '#1155CC', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR西日本225系電車; toretabi.jp entry-7303 — confirmed 130km/h capable 0/100番台 still running 新快速 alongside 223系ç, mid-2026' },
  { id: 'jp-jrw-221', fold: '221', name: '221系', country: 'JP', category: 'commuter', operator: 'JR西日本', topSpeedKmh: 120, nicknames: ['大和路快速', 'みやこ路快速', '快速'], debutYear: 1989, active: true, accentColor: '#EE3F2D', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR西日本221系電車; kansai-norikae.com miyakoji-rapid — confirmed still運用 大和路快速/みやこ路快速 as of 2026, and took over remaining 大和路線 duties after 201系\'s March 2025 retirement' },
  { id: 'jp-jrw-321', fold: '321', name: '321系', country: 'JP', category: 'commuter', operator: 'JR西日本', topSpeedKmh: 120, nicknames: ['JR京都線', 'JR神戸線', 'JR宝塚線'], debutYear: 2005, active: true, accentColor: '#F39800', silhouette: 'commuter', source: 'raillab.jp/series/292; ameblo.jp ra-tana entry-12958931004 — confirmed 39編成 based Aboshi/Akashi branch, still primary JR京都/神戸/宝塚/東西線 stock mid-2026' },
  { id: 'jp-jrw-207', fold: '207', name: '207系', country: 'JP', category: 'commuter', operator: 'JR西日本', topSpeedKmh: 120, nicknames: ['学研都市線', 'JR宝塚線'], debutYear: 1991, active: true, accentColor: '#009944', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR西日本207系電車; railf.jp — confirmed ongoing 体質改善 (refresh) program through 2026, no retirement announced, still core JR東西線/学研都市線 fleet' },
  { id: 'jp-jrw-521', fold: '521', name: '521系', country: 'JP', category: 'commuter', operator: 'JR西日本', topSpeedKmh: 120, nicknames: ['北陸本線普通', 'あいの風ライナー'], aliases: ['521系(JR西日本)', '521系(あいの風とやま鉄道)', '521系(IRいしかわ鉄道)', '521系(ハピラインふくい)'], debutYear: 2006, active: true, accentColor: '#F8B500', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR西日本521系電車; toretabi.jp entry-10627 — confirmed post-2024 Hokuriku Shinkansen extension handover split JR-West-owned units vs. 3rd-sector (あいの風/IR/ハピライン) fleets, all in daily service mid-2026' },
  { id: 'jp-jrw-115', fold: '115', name: '115系', country: 'JP', category: 'commuter', operator: 'JR西日本', topSpeedKmh: 100, nicknames: ['末期色', '岡山地区普通'], aliases: ['115系A編成', '115系D編成'], debutYear: 1963, active: true, retiresNote: 'G編成(食パン)引退・廃車回送済み(2026年7月); A/D編成のみ福塩線中心に限定運用継続、227系「Urara」増備完了後に全廃見込み', accentColor: '#FFD400', silhouette: 'commuter', source: 'railfromokayama2.com 2026/04/02 and 2026 hobidas rmnews/543030 — confirmed G編成 fully withdrawn July 2026, A/D編成 still in scheduled service (mainly 福塩線) as of the basis date, imminent full retirement expected' },
  { id: 'jp-jrw-113', fold: '113', name: '113系', country: 'JP', category: 'commuter', operator: 'JR西日本', topSpeedKmh: 100, nicknames: ['福知山地区最後の国鉄型'], aliases: ['113系5300番台', '113系S編成'], debutYear: 1963, active: true, retiresNote: '岡山地区は2025年で運用終了・全廃; 現存は吹田総合車両所福知山支所のS編成(2両×5本)のみ、日本最後の営業運転113系', accentColor: '#2E8B57', silhouette: 'commuter', source: 'note.com tc221_25 113系S編成運用表(2026.3.14改正版); railscenery.ever.jp 2026-04-30 — confirmed last 5 two-car S-sets running 綾部～城崎温泉/舞鶴線/宮福線, the last scheduled 113系 service in Japan as of mid-2026' },
  { id: 'jp-jrw-105', fold: '105', name: '105系', country: 'JP', category: 'commuter', operator: 'JR西日本', topSpeedKmh: 100, nicknames: ['福塩線普通', '宇部線普通'], debutYear: 1981, active: true, retiresNote: '福塩線・山口地区とも227系(500番台Urara/Kizashi)による置き換えが噂されるが2026年度改正では未発表', accentColor: '#8FBC3F', silhouette: 'commuter', source: 'railfromokayama2.com 2026/01/29; note.com yontyokuchanel 227系導入記事 — confirmed still in daily service on 福塩線 and 宇部線/小野田線 mid-2026, no confirmed retirement date yet' },
  { id: 'jp-jrw-125', fold: '125', name: '125系', country: 'JP', category: 'commuter', operator: 'JR西日本', topSpeedKmh: 100, nicknames: ['小浜線普通', '加古川線普通'], debutYear: 2003, active: true, accentColor: '#00A0E9', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR西日本125系電車; news.mynavi.jp 20230321-2632249 — confirmed ongoing daily 小浜線/加古川線/舞鶴線 single-car operation, no retirement signal found' },
  { id: 'jp-jrs-5000', fold: '5000', name: '5000系', country: 'JP', category: 'commuter', operator: 'JR四国', topSpeedKmh: 130, nicknames: ['マリンライナー'], aliases: ['5100形(2階建て)'], debutYear: 2003, active: true, accentColor: '#FFD400', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR四国5000系電車; ktm-models.co.jp — JR Shikoku\'s first double-decker EMU, always runs coupled with JR West\'s 223系5000番台 as a 5-car マリンライナー rapid between Takamatsu and Okayama' },
  { id: 'jp-jrs-7000', fold: '7000', name: '7000系', country: 'JP', category: 'commuter', operator: 'JR四国', topSpeedKmh: 110, nicknames: [], aliases: ['7200系(121系改造名義変更車)'], debutYear: 1990, active: true, accentColor: '#F8B62D', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR四国7000系電車; toretabi.jp 7200系 feature — JR四国\'s first VVVF EMU family, introduced with 1990 Iyo-Hojo–Iyoshi electrification; 7200系 is a 2016-2019 rebuild/renumbering of the earlier 121系, folded into the same family since it shares 7000系 running gear and couples with it' },
  { id: 'jp-jrk-813', fold: '813', name: '813系', country: 'JP', category: 'commuter', operator: 'JR九州', topSpeedKmh: 120, nicknames: ['福北ゆたか線'], debutYear: 1994, active: true, accentColor: '#DC241F', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR九州813系電車 — 85 sets/254 cars built 1994-2009, wide use across Kagoshima/Nagasaki/Sasebo/Nippo main lines and the 福北ゆたか線 corridor' },
  { id: 'jp-jrk-815', fold: '815', name: '815系', country: 'JP', category: 'commuter', operator: 'JR九州', topSpeedKmh: 120, nicknames: [], debutYear: 1999, active: true, accentColor: '#E4007F', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR九州815系電車 — debuted with 1999 豊肥本線 electrification (熊本-肥後大津), also displaced 423/457/475系 on 鹿児島線熊本地区 and 日豊線大分地区' },
  { id: 'jp-jrk-817', fold: '817', name: '817系', country: 'JP', category: 'commuter', operator: 'JR九州', topSpeedKmh: 120, nicknames: ['シーサイドライナー', 'なのはなDX'], debutYear: 2001, active: true, accentColor: '#00A0E9', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR九州817系電車 — debuted Oct 2001 with 福北ゆたか線 opening, since expanded to become JR九州\'s broadest-coverage AC suburban EMU family, replacing 475/457/717/415系 across most electrified lines' },
  { id: 'jp-jrk-821', fold: '821', name: '821系', country: 'JP', category: 'commuter', operator: 'JR九州', topSpeedKmh: 120, nicknames: [], debutYear: 2019, active: true, accentColor: '#00873C', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR九州821系電車; trafficnews.jp — commercial debut March 16 2019 as 415系 successor with SiC-MOSFET drives (~70% less power draw); as of April 2026, 10 three-car sets (30 cars) based at 熊本車両センター, covering 門司港-八代 鹿児島線, 福北ゆたか線 and one-man 豊肥線 runs' },
  { id: 'jp-jrk-811', fold: '811', name: '811系', country: 'JP', category: 'commuter', operator: 'JR九州', topSpeedKmh: 120, nicknames: [], debutYear: 1989, active: true, accentColor: '#00A650', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR九州811系電車 — debuted July 1989 for the Kitakyushu/Fukuoka 快速 network and 421系 replacement; 112 cars (28×4-car) built through 1993; recently undergoing VVVF (SiC/IGBT hybrid) retrofit from original thyristor control' },
  { id: 'jp-jrk-305', fold: '305', name: '305系', country: 'JP', category: 'commuter', operator: 'JR九州', topSpeedKmh: 110, nicknames: [], debutYear: 2015, active: true, accentColor: '#B5A642', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR九州305系電車 — debuted Feb 2015 replacing 103系1500番台 on 筑肥線/唐津線 and through-running with Fukuoka City Subway Airport Line; manual one-man operation progressively extended (2021 Meinohama-Chikuzen-Maebaru, 2024 to Karatsu/Nishi-Karatsu)' },
  { id: 'jp-jrk-303', fold: '303', name: '303系', country: 'JP', category: 'commuter', operator: 'JR九州', topSpeedKmh: 110, nicknames: [], debutYear: 1999, active: true, accentColor: '#003DA5', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/JR九州303系電車 — debuted 1999-2000 for post-double-tracking frequency increase on 筑肥線; 3 six-car sets (18 cars), ATO-equipped for through-running into Fukuoka City Subway' },
  { id: 'jp-jrk-415', fold: '415', name: '415系', country: 'JP', category: 'commuter', operator: 'JR九州', topSpeedKmh: 100, nicknames: ['関門仕様'], aliases: ['415系1500番台', '国鉄415系'], debutYear: 1986, active: true, accentColor: '#003DA5', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/国鉄415系電車; railfromokayama2.com 2026 / kumoyuni45.net — only the stainless 1500番台 (built 1986, ~40 years old) survives after steel-bodied cars retired 2022; sole remaining regular AC/DC dual-voltage type crossing the 関門トンネル dead-section into Shimonoseki (JR西 territory)' },
  { id: 'jp-keikyu-1000', fold: '京急1000', name: '京急1000形', country: 'JP', category: 'commuter', operator: '京浜急行電鉄', topSpeedKmh: 120, nicknames: ['新1000形'], aliases: ['1000形アルミ車(1〜5次車)', '1000形ステンレス車(6次車以降)', '京急1000形(2代)'], debutYear: 2002, active: true, accentColor: '#D70029', silhouette: 'commuter', source: 'ja.wikipedia.org/京急1000形電車(2代) — 2002 debut, 120km/h, standard Keikyu commuter EMU running through Toei Asakusa line to Keisei/Narita, riders\' everyday \'Keikyu train\'' },
  { id: 'jp-nishitetsu-9000', fold: '西鉄9000', name: '西鉄9000形', country: 'JP', category: 'commuter', operator: '西日本鉄道', topSpeedKmh: 110, nicknames: [], debutYear: 2017, active: true, accentColor: '#C8102E', silhouette: 'commuter', source: 'ja.wikipedia.org/wiki/西鉄9000形電車; 2025年4月時点で18編成43両を確認' },
  { id: 'jp-shinano-sr1', fold: 'SR1', name: 'SR1系', country: 'JP', category: 'commuter', operator: 'しなの鉄道', topSpeedKmh: 100, nicknames: ['しなのサンライズ', 'しなのサンセット', '軽井沢リゾート'], aliases: ['SR1系100番台', 'SR1系200番台', 'しなの鉄道SR1系'], debutYear: 2020, active: true, accentColor: '#E2574C', silhouette: 'commuter', source: 'ja.wikipedia しなの鉄道SR1系電車; shinanorailway.co.jp/sr1/' },
  { id: 'jp-chitetsu-16010', fold: '富山地鉄16010', name: '富山地鉄16010形', country: 'JP', category: 'commuter', operator: '富山地方鉄道', topSpeedKmh: 95, nicknames: ['アルプスエキスプレス'], aliases: ['元西武5000系レッドアロー'], debutYear: 1995, active: true, accentColor: '#C9A13B', silhouette: 'commuter', source: 'ja.wikipedia 富山地方鉄道16010形電車; tetsudo.com column/645' },
  { id: 'jp-chitetsu-10030', fold: '富山地鉄10030', name: '富山地鉄10030形', country: 'JP', category: 'commuter', operator: '富山地方鉄道', topSpeedKmh: 95, nicknames: [], aliases: ['元京阪3000系(初代・テレビカー)'], debutYear: 1991, active: true, accentColor: '#7A1F2B', silhouette: 'commuter', source: 'ja.wikipedia 京阪3000系電車(初代); uraken.net 富山地方鉄道10030形' },
  { id: 'jp-jre-e531', fold: 'E531', name: 'E531系', country: 'JP', category: 'commuter', operator: 'JR東日本', topSpeedKmh: 130, nicknames: [], debutYear: 2005, active: true, accentColor: '#003F6C', silhouette: 'commuter', source: 'JR東日本初の130km/h普通列車用交直流車、2005-07-09営業開始。上野東京ライン経由で品川（東京〜品川は東海道線籍）へ定期直通、3000番台は東北線黒磯〜新白河の定期シャトルを持つ (ja.wikipedia E531系・上野東京ライン; wdic.org; trafficnews.jp 128269; nta.co.jp; railf.jp 2026-05-02; fact-check 2026-07)' },
  { id: 'jp-jrk-bec819', fold: 'BEC819', name: 'BEC819系', country: 'JP', category: 'commuter', operator: 'JR九州', topSpeedKmh: 120, nicknames: ['DENCHA'], aliases: ['DENCHA', 'デンチャ'], debutYear: 2016, active: true, accentColor: '#3C8DBC', silhouette: 'commuter', source: '蓄電池電車DENCHA（DUAL ENERGY CHARGE TRAIN）、2016-10-19若松線（筑豊線若松〜折尾）デビュー、2019-03香椎線全列車置換（300番台）、2020-03改正から香椎〜博多の鹿児島線直通あり。直方配置36両で置換計画なし (ja.wikipedia BEC819系; toretabi.jp 7895; tetsudo.com/news/2212; trafficnews.jp 82377/84489; fact-check 2026-07)' },
  { id: 'jp-jrw-103', fold: '103', name: '103系', country: 'JP', category: 'commuter', operator: 'JR西日本', topSpeedKmh: 100, nicknames: [], aliases: ['103系3500番台', '103系3550番台'], debutYear: 1998, active: true, retiresNote: 'JR西日本2024-05株主向け開示の在来線173両投入（2025年度〜）に播但・加古川線103系置換が含まれると報道。置換車種（227系等）・運行終了日は未公表', accentColor: '#7B2B3A', silhouette: 'commuter', source: 'JR九州筑肥線を除き国内最後の定期103系。3500番台=播但線電化1998-03-14投入（2連9本・網干配置）、3550番台=加古川線電化2004-12-19投入（貫通扉付き先頭化改造）。2026-01時点の乗車記・置換考察記事で両線とも現役を確認、原形式は1963年デビュー (ja.wikipedia 103系・青緑1号; densha.life; nukezo 2025-08; train-times.net jrwest2025pre-3; kishanori 2026-01-03; fact-check 2026-07)' },
  { id: 'jp-jrh-h100', fold: 'H100', name: 'H100形', country: 'JP', category: 'dmu', operator: 'JR北海道', topSpeedKmh: 100, nicknames: ['DECMO'], aliases: ['H100形DECMO'], debutYear: 2020, active: true, accentColor: '#E85B04', silhouette: 'dmu', source: 'ja.wikipedia.org/wiki/JR北海道H100形気動車; jrhokkaido.co.jp 2019-09-11 press PDF on DECMO line rollout' },
  { id: 'jp-jrh-kiha150', fold: 'キハ150', name: 'キハ150形', country: 'JP', category: 'dmu', operator: 'JR北海道', topSpeedKmh: 110, nicknames: [], aliases: ['キハ150形0番台', 'キハ150形100番台'], debutYear: 1993, active: true, accentColor: '#7B5AA6', silhouette: 'dmu', source: 'ja.wikipedia.org/wiki/JR北海道キハ150形気動車; uraken.net キハ150形一般形気動車 feature' },
  { id: 'jp-jrh-kiha201', fold: 'キハ201', name: 'キハ201系', country: 'JP', category: 'dmu', operator: 'JR北海道', topSpeedKmh: 120, nicknames: [], aliases: ['キハ201系0番台'], debutYear: 1997, active: true, accentColor: '#005BAC', silhouette: 'dmu', source: 'ja.wikipedia.org/wiki/JR北海道キハ201系気動車; tetsudo.com column on the electric+diesel coupled-運転 rarity' },
  { id: 'jp-jr-kiha54', fold: 'キハ54', name: 'キハ54形', country: 'JP', category: 'dmu', operator: 'JR北海道・JR四国', topSpeedKmh: 95, nicknames: [], aliases: ['キハ54形0番台(JR四国)', 'キハ54形500番台(JR北海道)'], debutYear: 1986, active: true, accentColor: '#00913A', silhouette: 'dmu', source: 'ja.wikipedia.org/wiki/国鉄キハ54形気動車; mynavi.jp 2026-06-10 on 花咲線 summer 2026 augmented service using キハ54/キハ40' },
  { id: 'jp-jre-hbe210', fold: 'HBE210', name: 'HB-E210系', country: 'JP', category: 'dmu', operator: 'JR東日本', topSpeedKmh: 100, nicknames: ['仙石東北ライン(特別快速)'], debutYear: 2015, active: true, accentColor: '#3EA746', silhouette: 'dmu', source: 'ja.wikipedia.org/wiki/JR東日本HB-E210系気動車 + 4gousya.net 配置歴' },
  { id: 'jp-jre-hbe220', fold: 'HBE220', name: 'HB-E220系', country: 'JP', category: 'dmu', operator: 'JR東日本', topSpeedKmh: 100, nicknames: [], debutYear: 2025, active: true, accentColor: '#F8B500', silhouette: 'dmu', source: 'ja.wikipedia.org/wiki/JR東日本HB-E220系気動車 + JR東日本プレスリリース(2024年11月21日) + train-times.net(2026年3月14日 盛岡支社ダイヤ改正)' },
  { id: 'jp-jre-kiha100', fold: 'キハ100', name: 'キハ100系', country: 'JP', category: 'dmu', operator: 'JR東日本', topSpeedKmh: 95, nicknames: [], debutYear: 1990, active: true, accentColor: '#8FC31F', silhouette: 'dmu', source: 'ja.wikipedia.org/wiki/JR東日本キハ100系・キハ110系気動車 + train-fan.com/大船渡線キハ100置換記事' },
  { id: 'jp-jrc-kiha25', fold: 'キハ25', name: 'キハ25系', country: 'JP', category: 'dmu', operator: 'JR東海', topSpeedKmh: 95, nicknames: [], debutYear: 2011, active: true, accentColor: '#F39800', silhouette: 'dmu', source: 'ja.wikipedia.org/JR東海キハ25形気動車; railway.jr-central.co.jp/train/local/detail_03_10/ (運用線区: 高山線・太多線・紀勢線・参宮線, 代走で名松線)' },
  { id: 'jp-jrc-kiha75', fold: 'キハ75', name: 'キハ75系', country: 'JP', category: 'dmu', operator: 'JR東海', topSpeedKmh: 120, nicknames: ['快速みえ'], debutYear: 1993, active: true, accentColor: '#D9333F', silhouette: 'dmu', source: 'ja.wikipedia.org/JR東海キハ75形気動車; railway.jr-central.co.jp/train/local/detail_03_07/; railf.jp/news/2024/10/27 (transfer/expansion onto 高山線)' },
  { id: 'jp-jrw-kiha120', fold: 'キハ120', name: 'キハ120', country: 'JP', category: 'dmu', operator: 'JR西日本', topSpeedKmh: 100, nicknames: ['木次線', '姫新線', 'スーパー草津線代走'], aliases: ['キハ120形0番台', 'キハ120形300番台'], debutYear: 1991, active: true, accentColor: '#C8102E', silhouette: 'dmu', source: 'ja.wikipedia.org/wiki/JR西日本キハ120形気動車; uraken.net kiha120 — confirmed sole single-car DMU across ~10 JR西日本 local non-electrified lines, no retirement plan, still primary rolling stock mid-2026' },
  { id: 'jp-jrw-kiha126', fold: 'キハ126', name: 'キハ126系', country: 'JP', category: 'dmu', operator: 'JR西日本', topSpeedKmh: 100, nicknames: ['山陰リレー号代走', '鳥取・米子快速'], aliases: ['キハ121系', 'キハ126形0番台', 'キハ126・121系'], debutYear: 2000, active: true, accentColor: '#E85298', silhouette: 'dmu', source: 'ja.wikipedia.org/wiki/JR西日本キハ126系気動車; pahoo.org img20130829-152146 — confirmed 100km/h service max (130km/h-capable design) on 米子～鳥取～益田 corridor plus 因美線/境線, no retirement signal found' },
  { id: 'jp-jrs-kiha32', fold: 'キハ32', name: 'キハ32形', country: 'JP', category: 'dmu', operator: 'JR四国', topSpeedKmh: 95, nicknames: [], aliases: ['国鉄キハ32形'], debutYear: 1987, active: true, accentColor: '#8FBC3F', silhouette: 'dmu', source: 'ja.wikipedia.org/wiki/国鉄キハ32形気動車; shikoku-railway-note.com 2026 — 11 cars remain, all Matsuyama-based, running 予土線/内子線/予讃線 local services after Kochi-based units retired March 2025' },
  { id: 'jp-jrk-yc1', fold: 'YC1', name: 'YC1系', country: 'JP', category: 'dmu', operator: 'JR九州', topSpeedKmh: 110, nicknames: [], debutYear: 2020, active: true, accentColor: '#1B1464', silhouette: 'dmu', source: 'ja.wikipedia.org/wiki/JR九州YC1系気動車; tetsudo.com 2025 — debuted March 2020 on 佐世保線/大村線/長崎線 as JR九州\'s first diesel-electric hybrid; expanded July 2025 to cover 長崎線江北-小長井 replacing all remaining キハ47 locals west of Kanbara; 52 cars, all Sasebo-based, as of 2026' },
  { id: 'jp-jrk-kiha200', fold: 'キハ200', name: 'キハ200系', country: 'JP', category: 'dmu', operator: 'JR九州', topSpeedKmh: 110, nicknames: ['シーサイドライナー(初代)', 'なのはなDX(旧塗装)'], aliases: ['キハ220形'], debutYear: 1991, active: true, accentColor: '#0068B7', silhouette: 'dmu', source: 'ja.wikipedia.org/wiki/JR九州キハ200系気動車 — debuted 1991 with a then-advanced 331kW engine and claw-clutch transmission; currently covers all of 久大本線 and 豊肥本線大分-豊後竹田; キハ220形 single-cab variant folded in as the same family' },
  { id: 'jp-hisatsu-hsor100', fold: 'HSOR100', name: 'HSOR100形', country: 'JP', category: 'dmu', operator: '肥薩おれんじ鉄道', topSpeedKmh: 95, nicknames: ['おれんじ食堂'], aliases: ['HSOR-100A形', '肥薩おれんじ鉄道HSOR-100形'], debutYear: 2003, active: true, accentColor: '#FF8C00', silhouette: 'dmu', source: 'ja.wikipedia 肥薩おれんじ鉄道HSOR-100形気動車; ja.wikipedia おれんじ食堂' },
  { id: 'jp-jrs-1000', fold: '四国1000', name: '四国1000形', country: 'JP', category: 'dmu', operator: 'JR四国', topSpeedKmh: 110, nicknames: [], aliases: ['四国1200'], debutYear: 1990, active: true, retiresNote: '1次車（1990年製）は2027年度以降の新型ハイブリッド気動車による置換計画と報道、2次車以降はリニューアルで2030年度頃まで継続見込み', accentColor: '#ABC88B', silhouette: 'dmu', source: '1000形と1200形を1枚に統合：1200形は1000形56両中18両の1500形併結対応改造車（2006/2008年、原番号+200）で同一機関・台枠・110km/h、ja.wikipediaの1200形記事は1000形記事へのリダイレクト。1500形は別世代につき別カード。土讃線は高知配置1000形が担当（ごめん・なはり線直通含む） (ja.wikipedia 1000形; jr-shikoku.co.jp 1000型/1200型; itreni.net; tetsudo-ch.com 12889908; fact-check 2026-07)' },
  { id: 'jp-jrs-1500', fold: '四国1500', name: '四国1500形', country: 'JP', category: 'dmu', operator: 'JR四国', topSpeedKmh: 110, nicknames: [], debutYear: 2006, active: true, accentColor: '#ABC88B', silhouette: 'dmu', source: '2006〜2014年新製34両・徳島配置の最新一般気動車（コモンレール450PS・低床、旧国鉄形と併結不可でこれが1200形改造の理由）。ja.wikipediaで独立記事を持つ別世代につき単独カード。設計最高120km/h・営業最高110km/h (ja.wikipedia 1500形; jr-shikoku.co.jp 1500型; itreni.net; mynavi train2014-21; fact-check 2026-07)' },
  { id: 'cn-cr-crh1', fold: 'CRH1', name: 'CRH1', country: 'CN', category: 'cn-hsr', operator: '中国国家鉄路集団', topSpeedKmh: 250, nicknames: ['和谐号'], aliases: ['CRH1A', 'CRH1A-A', 'CRH1B', 'CRH1E', 'CRH1E-NG'], debutYear: 2007, active: true, accentColor: '#1A56A8', silhouette: 'cn-hsr', source: 'zh.wikipedia.org/CRH1型电力动车组; china-emu.cn CRH1A/CRH1E model pages, cross-checked with baike.baidu.com CRH1 entry' },
  { id: 'cn-cr-crh5', fold: 'CRH5', name: 'CRH5', country: 'CN', category: 'cn-hsr', operator: '中国国家鉄路集団', topSpeedKmh: 250, nicknames: ['和谐号'], aliases: ['CRH5A', 'CRH5A(250)', 'CRH5G', 'CRH5E'], debutYear: 2007, active: true, accentColor: '#0D3C78', silhouette: 'cn-hsr', source: 'zh.wikipedia.org/CRH5型电力动车组; china-emu.cn CRH5A model/series pages' },
  { id: 'cn-cr-crh6', fold: 'CRH6', name: 'CRH6', country: 'CN', category: 'cn-hsr', operator: '中国国家鉄路集団', topSpeedKmh: 200, nicknames: ['和谐号', '城际动车组'], aliases: ['CRH6A', 'CRH6A-A', 'CRH6F', 'CRH6F-A', 'Cinova'], debutYear: 2012, active: true, accentColor: '#2F6FB0', silhouette: 'cn-hsr', source: 'zh.wikipedia.org/CRH6型电力动车组; china-emu.cn Cinova/CRH6 series pages' },
  { id: 'cn-cr-crh380d', fold: 'CRH380D', name: 'CRH380D', country: 'CN', category: 'cn-hsr', operator: '中国国家鉄路集団', topSpeedKmh: 300, nicknames: ['和谐号'], aliases: ['CRH380D(统型)', 'CRH380DL'], debutYear: 2013, active: true, accentColor: '#1B4F9C', silhouette: 'cn-hsr', source: 'zh.wikipedia.org/CRH380D型电力动车组; china-emu.cn CRH380D series pages; baike.baidu.com CRH380D' },
];
